### ISSUE TITLE
【建议】对于本代码库贡献方式的建议

### ISSUE THREAD

**Issue by Harrypotterrrr** [TJ-CSCCG/TJCS-Course#10]
像我这样有很多从同济cs毕业的人可以对这个代码库贡献，上传自己的代码或者写的文档，但是pull request 太大下载不下来，将每个人加入contributer又不利于维护。 希望改进一下，更多的使用link 而不是将doc放入本repo中
（吐槽：同济cs的文档能共享就共享，因为写这东西一点用都没有，只能耽误时间。希望对学弟学妹们有用）

**Comment by skyleaworlder** [comment]
:yum: 谢谢学长的意见！
不得不说，一开始建立这个仓库，想法是比较混沌的，甚至都没有想清楚到底是要做什么。

* 一开始想做一个完善的 “课程资源共享”，可是发现很多版权书上传并不恰当，再加上 pdf 文件过大，下载不方便。于是这个想法就破灭了。
* 之后想依靠 README 来介绍这门课在当前这个阶段是什么样子，这门课的潜规则是什么。但是想到课程每年都在改，老师每年也可能有变化，于是如果不每年都写得话，就又会逐渐丧失意义。这个想法也破灭了。
* 再后面就想到可以做一个对课程教学内容的展示，和对相关学习资料的链接。但是这方面做的也不是很好。

于是就成了现在这样四不像的样子。
后续有考虑建立其他仓库来弥补目前的缺陷。比如 [TJCS-Assignment](https://github.com/TJ-CSCCG/TJCS-Assignment) 这种真的就只是用 link 来组织的仓库；再比如书单仓库（不过答应办事的同学咕咕咕了）……

目前的话……无论是从人脉方面，还是自身经历方面，学弟我都在尽量积攒当中……
未来，会有更好的想法的。

**Comment by Harrypotterrrr** [comment]
嗯嗯，加油😁
