### ISSUE TITLE
编译原理课程资料

### ISSUE THREAD

**Issue by BigCiLeng** [TJ-CSCCG/TJCS-Course#26]
求编译原理的课程ppt以供学习

**Comment by skyleaworlder** [comment]
课件属于二进制文件，上传到仓库中会对仓库进行二进制污染。将近一年前就已经停止对仓库大批量上传二进制文件。

对于过往课件，目前的建议是找上一级的学长学姐获取。

**Comment by BigCiLeng** [comment]
了解了！感谢
