### ISSUE TITLE
移除pdf文件以最小化仓库体积

### ISSUE THREAD

**Issue by ganler** [TJ-CSCCG/TJCS-Course#4]
## Problem

- 仓库体积过大，over 666 MB（我还没下完）
- 直接放盗版书似乎不太好....

## Solution 1

- 移除pdf文件，并rebase
- 列出书单即可，同学们有条件可自行购买，或走gen.lib http://gen.lib.rus.ec/

## Solution 2 

Git Large File Storage(LFS) https://git-lfs.github.com/

**Comment by ganler** [comment]
![image](https://user-images.githubusercontent.com/38074777/86810364-671d3a80-c0af-11ea-8661-bffe3cd4f7c1.png)

我觉得我可以睡觉去了。

**Comment by skyleaworlder** [comment]
:sob:

**Comment by skyleaworlder** [comment]
经过整改后，book 📂中的 pdf 尽数删除。
repo size 变为原来的 60% 左右。
已经算是没有什么可以继续删除的了。

后续考虑直接在 **README** 中添加 **“课程教材” 的下载链接**。
其余与课程无关的书籍移往其他仓库。
