### ISSUE TITLE
关于Roadmap

### ISSUE THREAD

**Issue by ganler** [TJ-CSCCG/TJCS-Course#6]
目前来看本仓库的用途类似于一个CourseHub用于大家一起维护课程资源。

私以为大容量存储并不适用于github，可以将其移到OneDrive这种地方加速下载。

再者是roadmap，书籍是资源，学习方向的建议也可以是，如课程指南，帮助同学们顺利完成课程而不至于最后轮到抄作业收尾的下场。[[PR REF]]: https://github.com/TJ-CSCCG/TJCS-Course/pull/5.

除此之外可以进行：

+ 实习面经分享
+ 保研经验分享
+ 出国经验分享

> 可以参考复旦的[火锅](https://github.com/fdu-cooks/fdu-gradhotpot)项目，但“火锅”的信息本质是闭源的。
> 个人认为我们可以在作者同意的情况下大方点采取open的方式。具体有个很好的学习[范例](https://github.com/SurviveSJTU/SurviveSJTUManual)，来自上海交大。

利用github这个平台的“everyone can be the author”的优势，可以集思广益。

BTW，当务之急还是将本项目推出去并吸引前辈们进行贡献，光靠现在几个人我认为是不够的，大家每个人花半小时贡献一点就能创造很大的价值。

**Comment by skyleaworlder** [comment]
谢谢 ganler 大佬的指导！
有关大文件，日后肯定会进行处理的。
这个仓库主要还是像它的名字一样——和 Course 相关。之后会把和课程无关的文件，比如 db/book 里面的 《高性能 MySQL》 这些移去，填到由 phdl 主管的 [Book](https://github.com/TJ-CSCCG/TJCS-Book) 中。

本科过的好快……好像也是时候考虑 考研、保研、实习，甚至有的同学早就到了准备 出国 的阶段了。
之前仓库没有怎么推广，一是对目前的完善程度不够自信，想要自己好好规整一下最初的行为；二就是人脉的问题……

会朝 issue 中提出的方向努力的。

**Comment by ganler** [comment]
Closed since it is not an issue anymore. Thanks for the amazing contributions. @skyleaworlder
