### ISSUE TITLE
【问题】visitor-badge service in Readme has been down for a while

### ISSUE THREAD

**Issue by CookiePieWw** [TJ-CSCCG/TJCS-Course#60]
The visitor badge service used in Readme has been down for a while, and I see no sign of recovery:
![visitors](https://visitor-badge.glitch.me/badge?page_id=TJ-CSCCG.TJCS-Course)

I tried several alternatives like [hits](https://hits.dwyl.com/) and another [visitor-badge](https://github.com/lizheming/visitor-badge), but all of them seems to reset the counter (or I made mistakes? I just tried on my own fork). I wonder if it's appropriate to switch to one of them, or just simply delete that badge?

If you prefer to switch, I recommand the latter since it's more like the previous one with consistent format:
![visitors](https://visitor-badge.lithub.cc/badge?page_id=TJ-CSCCG.TJCS-Course)

**Comment by skyleaworlder** [comment]
Sounds great! The badge you posted here seems to perform well. It would be appreciated if you could create a PR to address this issue.
